_wandb:
    value:
        cli_version: 0.23.1
        e:
            6sqwf41g95hksvvrxog9jku60i4gz4ro:
                args:
                    - --phase
                    - "1"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1819278561280"
                        used: "144319995904"
                email: vishnukadam459@gmail.com
                executable: /home/vishnu/.conda/envs/vishnu/bin/python3.11
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f402f344-6019-ae1d-0c6b-e686985df0da
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-fe31083e-643d-81f6-63a2-a5f302fb20d6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-51c8850e-df7e-c5e6-1619-2582d822765c
                host: gpu2
                memory:
                    total: "2151743655936"
                os: Linux-5.4.0-172-generic-x86_64-with-glibc2.31
                program: /home/vishnu/new_sfno_train/train.py
                python: CPython 3.11.14
                root: /home/vishnu/new_sfno_train
                slurm:
                    cluster_name: (null)
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "3"
                    gtids: "0"
                    job_account: iiser
                    job_cpus_per_node: "32"
                    job_end_time: "1785258081"
                    job_gid: "1031"
                    job_gpus: 5,6,7
                    job_id: "67430"
                    job_name: sfno
                    job_nodelist: gpu2
                    job_num_nodes: "1"
                    job_partition: GPU-AI_prio
                    job_qos: normal
                    job_start_time: "1783875681"
                    job_uid: "1029"
                    job_user: vishnu
                    jobid: "67430"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu2
                    nprocs: "1"
                    ntasks: "1"
                    pmix_timeout: "3000"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/vishnu/new_sfno_train
                    submit_host: fortytwo
                    task_pid: "519610"
                    tasks_per_node: "1"
                    topology_addr: gpu2
                    topology_addr_pattern: node
                    tres_per_task: cpu:32
                startedAt: "2026-07-12T17:01:39.889974Z"
                writerId: 6sqwf41g95hksvvrxog9jku60i4gz4ro
        m:
            - "1": phase4_step
              "6":
                - 3
              "7": []
            - "1": phase1_step
              "6":
                - 3
              "7": []
            - "1": phase3_step
              "6":
                - 3
              "7": []
            - "2": phase1/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": phase3/*
              "5": 3
              "6":
                - 1
              "7": []
            - "2": phase4/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 54
            "2":
                - 1
                - 54
            "3":
                - 1
                - 7
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
channels:
    value: 21
data_path:
    value: /home/bedartha/public/datasets/as_downloaded/weatherbench2/era5/1959-2023_01_10-6h-240x121_equiangular_with_poles_conservative.zarr
embed_dim:
    value: 384
hard_thresholding_fraction:
    value: 1
num_layers:
    value: 8
num_workers:
    value: 15
phase:
    value: "1"
phase1_ckpt_every:
    value: 1000
phase1_ckpt_name:
    value: sfno_phase1SPHERE_layernorm_{step}.pth
phase1_final_ckpt:
    value: sfno_phase1.pth
phase1_grad_clip:
    value: 32
phase1_gradient_steps:
    value: 100
phase1_log_every:
    value: 10
phase1_lr:
    value: 0.005
phase1_val_every:
    value: 10
phase1_warmup_steps:
    value: 10
phase3_ar_end:
    value: 4
phase3_ar_start:
    value: 2
phase3_ckpt_name:
    value: sfno_phase3_ar_{ar_steps}.pth
phase3_final_ckpt:
    value: sfno_phase3_final.pth
phase3_gradient_steps:
    value: 10
phase3_load_ckpt:
    value: sfno_phase1SPHERE_layernorm_10000.pth
phase3_log_every:
    value: 2
phase3_lr:
    value: 3e-05
phase3_val_every:
    value: 10
phase4_ckpt_every:
    value: 10
phase4_ckpt_name:
    value: sfno_phase4SPHERE_layernorm_{step}_final.pth
phase4_crop_h:
    value:
        - 64
        - 85
phase4_crop_w:
    value:
        - 40
        - 65
phase4_grad_clip:
    value: 32
phase4_gradient_steps:
    value: 10
phase4_load_ckpt:
    value: sfno_phase1SPHERE_layernorm_10000.pth
phase4_log_every:
    value: 10
phase4_lr:
    value: 5e-05
phase4_val_every:
    value: 10
scale_factor:
    value: 2
wandb_project:
    value: ERA5-train-distributed
